import type { Logger } from '@/platform/Logger';
import type { ProviderTraceContext } from '@/providers/types';
import type { VaultAdapter } from '@/storage/vaultAdapter';
import { CANVAS_BUDGETS } from './budgets';
import { CANVAS_LOG } from './loggingNamespaces';
import { generateCanvasRunId } from './runIdRegistry';
import type { CanvasMutex, CanvasOp } from './mutex';
import { createCanvasRefine, type CanvasRefineProvider, type RefineMessage } from './refine';
import { expandSourceHints, type CanvasMetadataCacheLike } from './plan';
import { fetchCanvasSources } from './fetch';
import { runExtractors, type CanvasExtractorProvider } from './extract';
import { reduceEntityGraph, type CanvasReducerProvider, ReducerInvalidError } from './reduce';
import { buildPageBasenameMap, resolveEntityFiles } from './resolveFiles';
import { WIKI_PAGES_DIR } from '@/agent/wiki/paths';
import { diffAgainstSidecar, buildTombstoneSummary, tryParseCurrentCanvas } from './diff';
import { layout, type LayoutHint, type LayoutPreset, autoSelect } from './layouts';
import { resolvePaletteId, type CanvasPaletteId } from './layouts/colorPalette';
import {
  assertTargetDoesNotExist,
  cleanupPreview,
  commitPreview,
  TargetExistsError,
  writePreview,
  writeSidecarFromState,
} from './writer';
import type {
  CanvasErrorPayload,
  CanvasFailedSource,
  CanvasPartial,
  CanvasPhase,
  CanvasState,
  CanvasTerminalState,
  PreviewingDecisionAdapter,
} from './state';
import type { Insights, SidecarV1, RunPlan } from './schemas';
import type { CanvasJson } from './canvasJson';

export interface CanvasPhaseEvent {
  readonly phase: CanvasPhase;
  readonly previewPath?: string;
  readonly fellBackTo?: string;
  readonly insights?: Insights;
  readonly error?: CanvasErrorPayload;
}

export type StartCanvasInput = {
  readonly threadId: string;
  readonly op: CanvasOp;
  readonly originalAsk: string;
  readonly targetPath?: string;
  readonly layoutAlgo?: LayoutHint;
  readonly paletteId?: CanvasPaletteId;
  readonly editInstruction?: string;
  readonly initialSidecar?: SidecarV1 | null;
  readonly initialCanvasJson?: CanvasJson | null;
  /**
   * If supplied, used as the runId for this run. Otherwise generated by
   * `generateCanvasRunId()`. Lets callers (e.g. the orchestrator) precompute
   * a runId so they can begin a Langfuse trace span keyed by runId BEFORE the
   * subgraph's first LLM call.
   */
  readonly runId?: string;
};

export interface SubgraphProvider
  extends CanvasRefineProvider, CanvasExtractorProvider, CanvasReducerProvider {}

export interface CanvasSubgraphDeps {
  readonly mutex: CanvasMutex;
  readonly vault: VaultAdapter;
  readonly metadataCache?: CanvasMetadataCacheLike;
  readonly provider: SubgraphProvider;
  readonly model: () => string;
  readonly temperature?: () => number;
  readonly maxTokens?: () => number;
  readonly previewing: PreviewingDecisionAdapter;
  readonly logger?: Logger;
  readonly traceConfig?: ProviderTraceContext;
  readonly clock?: () => Date;
  readonly cancelGracePeriodMs?: number;
  /**
   * Vault directories scanned (recursively) to build a slug→path index that
   * extends `resolveEntityFiles` beyond per-run sources. Defaults to
   * `[WIKI_PAGES_DIR]`. Pass `[]` to disable the broad fallback.
   */
  readonly pagesDirs?: readonly string[];
}

export interface RunHandle {
  readonly runId: string;
  readonly op: CanvasOp;
  readonly threadId: string;
  readonly originalAsk: string;
  readonly targetPath: string;
  abort(): void;
  readonly terminal: Promise<CanvasTerminalState>;
  subscribe(listener: (event: CanvasPhaseEvent) => void): () => void;
}

export type StartCanvasResult =
  | { readonly ok: true; readonly handle: RunHandle }
  | {
      readonly ok: false;
      readonly busy: { readonly activeRunId: string; readonly activeOp: CanvasOp };
    };

export function startCanvasRun(
  deps: CanvasSubgraphDeps,
  input: StartCanvasInput,
): StartCanvasResult {
  const targetPath = input.targetPath ?? defaultCanvasTargetPath(input.originalAsk);
  const runId = input.runId ?? generateCanvasRunId();
  const acquireResult = deps.mutex.acquire(targetPath, runId, input.op);
  if (!acquireResult.ok) {
    return { ok: false, busy: acquireResult.busy };
  }
  const ctrl = new AbortController();
  const start = (deps.clock ?? (() => new Date()))();
  let aborted = false;
  let inUninterruptibleWrite = false;
  const onAbort = (): void => {
    if (inUninterruptibleWrite) return;
    aborted = true;
    ctrl.abort();
  };

  const listeners = new Set<(event: CanvasPhaseEvent) => void>();
  let lastEmittedPhase: CanvasPhase | null = null;
  let currentState: CanvasState | null = null;
  const buildEvent = (state: CanvasState, error?: CanvasErrorPayload): CanvasPhaseEvent => {
    const event: { -readonly [K in keyof CanvasPhaseEvent]: CanvasPhaseEvent[K] } = {
      phase: state.phase,
    };
    if (state.previewPath !== null && state.previewPath !== undefined)
      event.previewPath = state.previewPath;
    if (state.fellBackTo !== undefined) event.fellBackTo = state.fellBackTo;
    if (state.insights !== null && state.insights !== undefined) event.insights = state.insights;
    if (error !== undefined) event.error = error;
    return event;
  };
  const emit = (state: CanvasState, error?: CanvasErrorPayload): void => {
    if (lastEmittedPhase === state.phase && error === undefined) return;
    lastEmittedPhase = state.phase;
    const event = buildEvent(state, error);
    for (const l of listeners) {
      try {
        l(event);
      } catch {
        /* listener failures isolated */
      }
    }
  };

  const terminal = (async (): Promise<CanvasTerminalState> => {
    const state: CanvasState = freshState({
      runId,
      threadId: input.threadId,
      op: input.op,
      originalAsk: input.originalAsk,
      targetPath,
      paletteId: resolvePaletteId(input.paletteId),
      ...(input.initialSidecar !== undefined && input.initialSidecar !== null
        ? { initialSidecar: input.initialSidecar }
        : {}),
      ...(input.initialCanvasJson !== undefined && input.initialCanvasJson !== null
        ? { initialCanvasJson: input.initialCanvasJson }
        : {}),
    });
    let mutableState = state;
    currentState = mutableState;
    let pageBasenamesCache: ReadonlyMap<string, string> | null = null;
    const getPageBasenames = async (): Promise<ReadonlyMap<string, string> | null> => {
      if (pageBasenamesCache !== null) return pageBasenamesCache;
      const dirs = deps.pagesDirs ?? [WIKI_PAGES_DIR];
      if (dirs.length === 0) return null;
      try {
        pageBasenamesCache = await buildPageBasenameMap(deps.vault, dirs);
      } catch {
        pageBasenamesCache = new Map();
      }
      return pageBasenamesCache;
    };
    const terminate = async (
      st: CanvasState,
      kind: 'done' | 'cancelled' | 'error',
      error?: CanvasErrorPayload,
    ): Promise<CanvasTerminalState> => {
      const term: CanvasState = { ...st, phase: kind };
      currentState = term;
      emit(term, error);
      return finalize({
        state: term,
        deps,
        start,
        kind,
        ...(error !== undefined ? { error } : {}),
      });
    };
    try {
      // eslint-disable-next-line no-constant-condition
      while (true) {
        currentState = mutableState;
        emit(mutableState);
        if (aborted && !inUninterruptibleWrite) {
          return terminate(mutableState, 'cancelled');
        }
        if (mutableState.phase === 'preparing') {
          const r = await preparingPhase(mutableState, deps, ctrl.signal, input);
          if (r.kind === 'error') return terminate(mutableState, 'error', r.error);
          if (r.kind === 'question') {
            // No widget interaction in v1 driver — treat as terminal error if cap hit.
            mutableState = { ...mutableState, questionCount: mutableState.questionCount + 1 };
            if (mutableState.questionCount >= CANVAS_BUDGETS.refineClarifyMax) {
              return terminate(mutableState, 'error', {
                code: 'refine_unresolved',
                message: 'refine question cap exhausted',
              });
            }
            continue;
          }
          mutableState = { ...mutableState, runPlan: r.plan, phase: 'planning' };
          continue;
        }
        if (mutableState.phase === 'planning') {
          const expanded = await expandSourceHints({
            hints: mutableState.runPlan!.sourceHints,
            vault: deps.vault,
            ...(deps.metadataCache !== undefined ? { metadataCache: deps.metadataCache } : {}),
          });
          if (expanded.items.length === 0 && mutableState.op === 'create') {
            return terminate(mutableState, 'error', {
              code: 'no_sources',
              message:
                'Refine produced no sources — provide specific files, tags, URLs, or attachments in the ask.',
            });
          }
          mutableState = { ...mutableState, sources: expanded.items, phase: 'fetching' };
          continue;
        }
        if (mutableState.phase === 'fetching') {
          if (mutableState.op === 'create' && mutableState.targetPath !== '') {
            const guard = await assertTargetDoesNotExist({
              adapter: deps.vault,
              targetPath: mutableState.targetPath,
            });
            if (!guard.ok) {
              const code =
                guard.error instanceof TargetExistsError ? 'target_path_exists' : 'invalid_path';
              return terminate(mutableState, 'error', { code, message: guard.error.message });
            }
          }
          const fetchResult = await fetchCanvasSources(
            mutableState.sources,
            { vault: deps.vault },
            ctrl.signal,
          );
          if (aborted && !inUninterruptibleWrite) {
            return terminate({ ...mutableState, fetched: fetchResult.items }, 'cancelled');
          }
          if (fetchResult.failedAll && fetchResult.items.length > 0) {
            return terminate({ ...mutableState, fetched: fetchResult.items }, 'error', {
              code: 'all_sources_failed',
              message: 'every source fetch failed',
            });
          }
          mutableState = { ...mutableState, fetched: fetchResult.items, phase: 'extracting' };
          continue;
        }
        if (mutableState.phase === 'extracting') {
          const extracted = await runExtractors(
            {
              items: mutableState.fetched,
              schema: {
                entityTypes: mutableState.runPlan!.entityTypes,
                relationTypes: mutableState.runPlan!.relationTypes,
              },
              originalAsk: mutableState.originalAsk,
              signal: ctrl.signal,
              ...(deps.traceConfig !== undefined ? { traceConfig: deps.traceConfig } : {}),
            },
            {
              provider: deps.provider,
              model: deps.model,
              ...(deps.temperature !== undefined ? { temperature: deps.temperature } : {}),
              ...(deps.maxTokens !== undefined ? { maxTokens: deps.maxTokens } : {}),
              ...(deps.logger !== undefined ? { logger: deps.logger } : {}),
            },
          );
          if (aborted && !inUninterruptibleWrite) {
            return terminate(
              {
                ...mutableState,
                extractorOutputs: extracted.outputs,
                extractorErrors: extracted.perSourceErrors as readonly CanvasFailedSource[],
              },
              'cancelled',
            );
          }
          mutableState = {
            ...mutableState,
            extractorOutputs: extracted.outputs,
            extractorErrors: extracted.perSourceErrors as readonly CanvasFailedSource[],
            phase: 'reducing',
          };
          continue;
        }
        if (mutableState.phase === 'reducing') {
          try {
            const pageBasenames = await getPageBasenames();
            const reduced = await reduceEntityGraph(
              {
                outputs: mutableState.extractorOutputs.values(),
                signal: ctrl.signal,
                ...(mutableState.runPlan !== null
                  ? { relationTypes: mutableState.runPlan.relationTypes }
                  : {}),
                ...(deps.traceConfig !== undefined ? { traceConfig: deps.traceConfig } : {}),
              },
              {
                provider: deps.provider,
                model: deps.model,
                ...(deps.temperature !== undefined ? { temperature: deps.temperature } : {}),
                ...(deps.maxTokens !== undefined ? { maxTokens: deps.maxTokens } : {}),
                ...(deps.logger !== undefined ? { logger: deps.logger } : {}),
                ...(pageBasenames !== null ? { pageBasenames } : {}),
              },
            );
            const resolvedGraph = resolveEntityFiles({
              graph: reduced.graph,
              fetched: mutableState.fetched,
              ...(deps.metadataCache !== undefined ? { metadataCache: deps.metadataCache } : {}),
              ...(pageBasenames !== null ? { pageBasenames } : {}),
            });
            mutableState = {
              ...mutableState,
              graph: resolvedGraph,
              insights: reduced.insights,
              phase: mutableState.op === 'create' ? 'laying_out' : 'diffing',
            };
            continue;
          } catch (err) {
            if (err instanceof ReducerInvalidError) {
              return terminate(mutableState, 'error', {
                code: 'reduce_invalid',
                message: err.message,
              });
            }
            throw err;
          }
        }
        if (mutableState.phase === 'diffing') {
          const sidecar = input.initialSidecar;
          if (sidecar === null || sidecar === undefined) {
            return terminate(mutableState, 'error', {
              code: 'sidecar_missing',
              message: 'content_edit requires an existing sidecar',
            });
          }
          const parsed = await tryParseCurrentCanvas(deps.vault, mutableState.targetPath);
          if (!parsed.ok) {
            return terminate(mutableState, 'error', {
              code: 'canvas_parse_failed',
              message: parsed.error.message,
            });
          }
          const diff = diffAgainstSidecar({
            newGraph: mutableState.graph!,
            sidecar,
            currentCanvasJson: parsed.value,
          });
          const summary = buildTombstoneSummary(diff.removed, diff.edgesRemoved, sidecar);
          mutableState = { ...mutableState, diff, tombstoneSummary: summary, phase: 'laying_out' };
          continue;
        }
        if (mutableState.phase === 'laying_out') {
          const preset = pickPreset(mutableState, input);
          const lockedCoords = mutableState.diff?.lockedCoords ?? {};
          const addedIds = new Set(mutableState.diff?.added ?? []);
          const result = layout({
            graph: mutableState.graph!,
            preset,
            lockedCoords,
            addedIds,
            budgets: {
              freeSpacePadPx: CANVAS_BUDGETS.freeSpacePadPx,
              bboxPadding: CANVAS_BUDGETS.bboxPadding,
            },
            paletteId: mutableState.paletteId,
          });
          mutableState = {
            ...mutableState,
            canvasJson: result.canvas,
            ...(result.fellBackTo !== undefined ? { fellBackTo: result.fellBackTo } : {}),
            phase: 'previewing',
          };
          continue;
        }
        if (mutableState.phase === 'previewing') {
          const written = await writePreview({
            adapter: deps.vault,
            targetPath: mutableState.targetPath,
            canvasJson: mutableState.canvasJson!,
          });
          if (!written.ok) {
            return terminate(mutableState, 'error', {
              code: 'preview_write_failed',
              message: written.error.message,
            });
          }
          mutableState = { ...mutableState, previewPath: written.value.previewPath };
          // Re-emit `previewing` so subscribers see the previewPath now that it exists.
          lastEmittedPhase = null;
          emit(mutableState);

          const decision = await deps.previewing.awaitDecision(mutableState);
          if (aborted) {
            await cleanupPreview({ adapter: deps.vault, previewPath: written.value.previewPath });
            return terminate(mutableState, 'cancelled');
          }
          if (decision.kind === 'cancel') {
            await cleanupPreview({ adapter: deps.vault, previewPath: written.value.previewPath });
            return terminate(mutableState, 'cancelled');
          }
          if (decision.kind === 'edit') {
            const nextIter = mutableState.editIterations + 1;
            if (nextIter >= CANVAS_BUDGETS.editIterationsMax) {
              await cleanupPreview({ adapter: deps.vault, previewPath: written.value.previewPath });
              return terminate(mutableState, 'error', {
                code: 'edit_iterations_exhausted',
                message: 'edit cap exceeded',
              });
            }
            const nextHistory: RefineMessage[] = [
              ...mutableState.refineHistory,
              { role: 'user', content: decision.instruction },
            ];
            await cleanupPreview({ adapter: deps.vault, previewPath: written.value.previewPath });
            mutableState = {
              ...mutableState,
              refineHistory: nextHistory,
              editIterations: nextIter,
              previewPath: null,
              phase: 'preparing',
            };
            continue;
          }
          // approve
          mutableState = { ...mutableState, phase: 'writing' };
          continue;
        }
        if (mutableState.phase === 'writing') {
          inUninterruptibleWrite = true;
          try {
            const commit = await commitPreview({
              adapter: deps.vault,
              previewPath: mutableState.previewPath!,
              targetPath: mutableState.targetPath,
            });
            if (!commit.ok) {
              await cleanupPreview({ adapter: deps.vault, previewPath: mutableState.previewPath! });
              return terminate(mutableState, 'error', {
                code: 'commit_preview_failed',
                message: commit.error.message,
              });
            }
            const sidecar: SidecarV1 = {
              schemaVersion: 1,
              runId: mutableState.runId,
              schema:
                mutableState.runPlan !== null
                  ? {
                      entityTypes: mutableState.runPlan.entityTypes,
                      relationTypes: mutableState.runPlan.relationTypes,
                    }
                  : (input.initialSidecar?.schema ?? { entityTypes: [], relationTypes: [] }),
              entityGraph: mutableState.graph!,
              coordMap: buildCoordMap(mutableState.canvasJson!),
              tombstones: [
                ...(input.initialSidecar?.tombstones ?? []),
                ...(mutableState.diff?.removed ?? []),
              ],
              edgeTombstones: [
                ...(input.initialSidecar?.edgeTombstones ?? []),
                ...(mutableState.diff?.edgesRemoved ?? []),
              ],
              lastRunAt: new Date().toISOString(),
            };
            const sideWrite = await writeSidecarFromState({
              adapter: deps.vault,
              canvasVaultPath: mutableState.targetPath,
              sidecar,
            });
            if (!sideWrite.ok) {
              return terminate(mutableState, 'error', {
                code: 'sidecar_write_failed',
                message: sideWrite.error.message,
              });
            }
            mutableState = { ...mutableState, sidecar, phase: 'done' };
          } finally {
            inUninterruptibleWrite = false;
          }
          continue;
        }
        if (mutableState.phase === 'done') {
          return terminate(mutableState, 'done');
        }
        // Should never reach here.
        return terminate(mutableState, 'error', {
          code: 'unknown_phase',
          message: `unknown phase ${mutableState.phase}`,
        });
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      if (mutableState.previewPath !== null) {
        await cleanupPreview({ adapter: deps.vault, previewPath: mutableState.previewPath }).catch(
          () => undefined,
        );
      }
      return terminate(mutableState, 'error', { code: 'subgraph_threw', message });
    } finally {
      acquireResult.release();
    }
  })();

  return {
    ok: true,
    handle: {
      runId,
      op: input.op,
      threadId: input.threadId,
      originalAsk: input.originalAsk,
      targetPath,
      abort: onAbort,
      terminal,
      subscribe(listener) {
        listeners.add(listener);
        if (currentState !== null) {
          try {
            listener(buildEvent(currentState));
          } catch {
            /* listener failures isolated */
          }
        }
        return (): void => {
          listeners.delete(listener);
        };
      },
    },
  };
}

interface FinalizeArgs {
  readonly state: CanvasState;
  readonly deps: CanvasSubgraphDeps;
  readonly start: Date;
  readonly kind: 'done' | 'cancelled' | 'error';
  readonly error?: CanvasErrorPayload;
}

async function finalize(args: FinalizeArgs): Promise<CanvasTerminalState> {
  const now = (args.deps.clock ?? (() => new Date()))();
  const durationMs = now.getTime() - args.start.getTime();
  if (args.kind !== 'done' && args.state.previewPath !== null) {
    await cleanupPreview({ adapter: args.deps.vault, previewPath: args.state.previewPath }).catch(
      () => undefined,
    );
  }
  args.deps.logger?.debug(CANVAS_LOG.create.transition, {
    runId: args.state.runId,
    op: args.state.op,
    phase: args.kind,
  });
  const partial = buildPartial(args.state);
  return {
    phase: args.kind,
    runId: args.state.runId,
    path: args.state.targetPath,
    op: args.state.op,
    ...(args.state.insights !== null ? { insights: args.state.insights } : {}),
    ...(partial !== null ? { partial } : {}),
    ...(args.error !== undefined ? { error: args.error } : {}),
    durationMs,
    paletteId: args.state.paletteId,
  };
}

function buildPartial(state: CanvasState): CanvasPartial | null {
  const fetchedSources = state.fetched
    .filter((it) => it.status === 'fetched')
    .map((it) => it.fetched!.sourceRef);
  const extractedSources = Array.from(state.extractorOutputs.keys());
  const failedSources: CanvasFailedSource[] = [];
  for (const it of state.fetched) {
    if (it.status === 'error') {
      failedSources.push({
        ref: it.source.resolvedRef,
        code: it.errorCode ?? 'fetch_failed',
        message: it.errorMessage ?? 'fetch failed',
      });
    }
  }
  for (const e of state.extractorErrors) failedSources.push(e);
  if (
    fetchedSources.length === 0 &&
    extractedSources.length === 0 &&
    failedSources.length === 0 &&
    state.previewPath === null
  ) {
    return null;
  }
  const partial: CanvasPartial = {
    fetchedSources,
    extractedSources,
    ...(state.previewPath !== null ? { previewPath: state.previewPath } : {}),
    ...(failedSources.length > 0 ? { failedSources } : {}),
  };
  return partial;
}

function freshState(args: {
  runId: string;
  threadId: string;
  op: CanvasOp;
  originalAsk: string;
  targetPath: string;
  paletteId: CanvasPaletteId;
  initialSidecar?: SidecarV1;
  initialCanvasJson?: CanvasJson;
}): CanvasState {
  if (args.op === 'layout_edit' && args.initialSidecar !== undefined) {
    const sidecar = args.initialSidecar;
    const synthDiff =
      args.initialCanvasJson !== undefined
        ? diffAgainstSidecar({
            newGraph: sidecar.entityGraph,
            sidecar,
            currentCanvasJson: args.initialCanvasJson,
          })
        : {
            kept: sidecar.entityGraph.entities.map((e) => ({ id: e.id, locked: true })),
            added: [] as readonly string[],
            removed: [] as readonly string[],
            edgesRemoved: [],
            lockedCoords: { ...sidecar.coordMap } as Record<
              string,
              { x: number; y: number; w: number; h: number }
            >,
          };
    return {
      runId: args.runId,
      threadId: args.threadId,
      op: args.op,
      originalAsk: args.originalAsk,
      targetPath: args.targetPath,
      phase: 'laying_out',
      editIterations: 0,
      questionCount: 0,
      refineHistory: [],
      runPlan: null,
      sources: [],
      fetched: [],
      extractorOutputs: new Map(),
      extractorErrors: [],
      graph: sidecar.entityGraph,
      insights: null,
      diff: synthDiff,
      canvasJson: null,
      previewPath: null,
      sidecar,
      tombstoneSummary: undefined,
      fellBackTo: undefined,
      paletteId: args.paletteId,
    };
  }
  return {
    runId: args.runId,
    threadId: args.threadId,
    op: args.op,
    originalAsk: args.originalAsk,
    targetPath: args.targetPath,
    phase: 'preparing',
    editIterations: 0,
    questionCount: 0,
    refineHistory: [],
    runPlan: null,
    sources: [],
    fetched: [],
    extractorOutputs: new Map(),
    extractorErrors: [],
    graph: null,
    insights: null,
    diff: null,
    canvasJson: null,
    previewPath: null,
    sidecar: args.initialSidecar ?? null,
    tombstoneSummary: undefined,
    fellBackTo: undefined,
    paletteId: args.paletteId,
  };
}

async function preparingPhase(
  state: CanvasState,
  deps: CanvasSubgraphDeps,
  signal: AbortSignal,
  input: StartCanvasInput,
): Promise<
  | { kind: 'plan'; plan: RunPlan }
  | { kind: 'question'; question: string }
  | { kind: 'error'; error: CanvasErrorPayload }
> {
  const refine = createCanvasRefine({
    provider: deps.provider,
    model: deps.model,
    ...(deps.temperature !== undefined ? { temperature: deps.temperature } : {}),
    ...(deps.maxTokens !== undefined ? { maxTokens: deps.maxTokens } : {}),
    ...(deps.logger !== undefined ? { logger: deps.logger } : {}),
  });
  const ask =
    state.editIterations === 0
      ? state.originalAsk
      : `${state.originalAsk}\n\nUser edits: ${state.refineHistory
          .filter((m) => m.role === 'user')
          .map((m) => m.content)
          .join('\n---\n')}`;
  void input;
  const decision = await refine.step({
    originalAsk: ask,
    history: state.refineHistory,
    targetPath: state.targetPath,
    questionCount: state.questionCount,
    signal,
    ...(state.tombstoneSummary !== undefined ? { tombstoneSummary: state.tombstoneSummary } : {}),
    ...(deps.traceConfig !== undefined ? { traceConfig: deps.traceConfig } : {}),
  });
  if (decision.kind === 'plan') return { kind: 'plan', plan: decision.plan };
  if (decision.kind === 'question') return { kind: 'question', question: decision.question };
  return {
    kind: 'error',
    error: { code: decision.code, message: decision.message ?? decision.code },
  };
}

function pickPreset(state: CanvasState, input: StartCanvasInput): LayoutPreset {
  const hint = input.layoutAlgo ?? state.runPlan?.layoutHint ?? 'auto';
  if (hint !== 'auto') return hint;
  return autoSelect(state.graph!);
}

function buildCoordMap(canvas: {
  nodes: readonly { id: string; x: number; y: number; width: number; height: number }[];
}): Record<string, { x: number; y: number; w: number; h: number }> {
  const out: Record<string, { x: number; y: number; w: number; h: number }> = {};
  for (const n of canvas.nodes) {
    out[n.id] = { x: n.x, y: n.y, w: n.width, h: n.height };
  }
  return out;
}

export function defaultCanvasTargetPath(originalAsk: string): string {
  return `canvases/${slug(originalAsk)}.canvas`;
}

function slug(s: string): string {
  return (
    s
      .toLowerCase()
      .normalize('NFKD')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'canvas'
  );
}
