export const ASK_USER_QUESTION_DESCRIPTION = [
  "Ask the user a single, specific question and wait for their answer. The answer is returned to you as the tool result. Most useful inside plan mode to resolve a structural choice the user's intent leaves ambiguous (flat vs hierarchical, MOC vs tag-driven, one deep note vs several connected notes).",
  '',
  '## When to use',
  '',
  '- A structural decision in a note-authoring task could reasonably go several ways and the user has not signalled a preference.',
  '- You need a short, specific piece of information from the user (a folder name, a tag, a chapter count) before continuing.',
  '',
  '## When NOT to use',
  '',
  '- Do NOT use this to ask "is the plan okay?" or "should I proceed?" — ExitPlanMode is the approval mechanism for plans.',
  '- Do NOT use this for open-ended discussion or to explain what you are going to do — write that in plain prose instead.',
  '- Do NOT use this when the user already gave specific instructions.',
  '',
  '## How to phrase',
  '',
  '- Provide 2–4 concrete `options` whenever possible. Each option should be mutually exclusive and short (≤ 80 chars). The user can always pick "Other" to provide free text.',
  '- Omit `options` only when the answer is genuinely freeform — a title, a folder path, a short phrase.',
  '- Use `multiSelect: true` only when the choices are not mutually exclusive (e.g. "Which of these tags should the note carry?").',
  '- Set a short `header` (≤ 20 chars) to label the question category — e.g. "Structure", "Naming", "Format".',
  '',
  '## Examples',
  '',
  '- question: "Should the chapters live as folders with sub-notes, or as flat files with frontmatter ordering?", options: ["folders", "flat"], header: "Structure".',
  '- question: "Which folder should the new project hub live in?", options: ["Areas/Projects", "Projects", "Vault root"], header: "Location".',
  '- question: "What should the hub note be titled?" (freeform — no options), header: "Naming".',
].join('\n');
