export const TASK_TOOL_DESCRIPTION = [
  "Spawn an isolated subagent to perform a self-contained task and return only its final summary, keeping this conversation's context small.",
  '',
  'When to use:',
  '- Opaque multi-step exploration where only the conclusion matters (deep search across many notes, multi-file investigation, batch lookups).',
  '- Any job that would burn many tool round-trips but whose intermediate output the user does not need to see.',
  '',
  'How it works:',
  '- The subagent runs in a fresh thread with no history, no focused-file context, and no slash-skill envelope.',
  '- It inherits your tools EXCEPT `task`, `delegate_external`, `delegate_canvas_*`, `EnterPlanMode`, `ExitPlanMode`, and `AskUserQuestion`.',
  '- Write-capable tools the subagent calls will still surface a confirmation dialog to the user in this chat.',
  '- A live widget appears in chat showing phase (preparing → running → done) and tool-call count. Internal text/tool blocks are NOT mirrored to chat.',
  "- The subagent's final assistant message becomes the `summary` field of the result you receive.",
  '',
  'Args:',
  '- `prompt` (required): self-contained instruction for the subagent. Restate every fact, file path, and constraint — the subagent sees none of this conversation. Describe the desired outcome and final-summary shape, not the steps.',
  '- `summaryInstructions` (optional): a shape constraint for the final answer (e.g. "bullet list of paths", "JSON `{path, score}[]`"). When omitted, the subagent returns free-form prose.',
  '- `timeoutMs` (optional): wall-clock cap in ms. Defaults to 600_000 (10 min); max 1_800_000 (30 min).',
  '',
  'Counter-indications — do NOT use `task` when:',
  '- The job needs back-and-forth clarification with the user (subagent cannot ask).',
  '- The job needs plan-mode review (subagent cannot enter plan mode).',
  '- It is a single tool call (just call the tool directly).',
  '- The user explicitly wants to see every intermediate step.',
].join('\n');
